
bind_addr = "8080"                 # port of apiserver
secret_key = "secret key"          # secret key for jwt
jwt_time = 60                      # jwt lifetime in minuts

postgres_user = "postgres"
postgres_password = "password"
postgres_host = "db"               # name of container in docker-compose (or localhost for debug without docker)
postgres_port = "5432"
postgres_dbname = "restapi_dev"
postgres_ssl = "disable"

redis_host = "redis"
redis_port = "6379"
redis_pass = ""
redis_db = 0
redis_exp = 60                    # redis var lifetime in seconds

rabbit_url = "amqp://guest:guest@rabbitmq:5672/"

mailer_exp = 60                   # mailer waiting time in seconds